# Generated by Django 5.2.4 on 2026-01-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_cabinbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinbooking',
            name='cabin_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cabinbooking',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cabinbooking',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
