# Generated by Django 5.2.4 on 2026-01-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_alter_cabinbooking_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinbooking',
            name='assigned_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
