# Generated by Django 5.2.4 on 2026-01-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_cabinbooking_assigned_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Package', 'Package'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Package', max_length=20),
        ),
    ]
