# Generated by Django 5.2.4 on 2026-01-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Bags and Travel', 'Bags and Travel'), ('Medicine', 'Medicine'), ('Mobile', 'Mobile'), ('Books', 'Books'), ('Foods', 'Foods')], default='Fashion', max_length=50),
        ),
    ]
