# Generated by Django 5.2.4 on 2026-01-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered')], max_length=50, null=True),
        ),
    ]
