# Generated by Django 5.2.4 on 2026-01-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Bags and Travel', 'Bags and Travel'), ('Medicine', 'Medicine'), ('Mobiles', 'Mobiles'), ('Books', 'Books'), ('Food', 'Food'), ('Watch', 'Watch'), ('Groceries', 'Groceries'), ('Furniture & Décor', 'Furniture & Décor'), ('Woman Dress', 'Woman Dress'), ('Kitchen Utensils', 'Kitchen Utensils')], default='Fashion', max_length=50),
        ),
    ]
