# Generated by Django 5.2.4 on 2026-01-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Bags and Travel', 'Bags and Travel'), ('Medicine', 'Medicine'), ('Mobiles', 'Mobiles'), ('Books', 'Books'), ('Food', 'Food'), ('Watch', 'Watch'), ('Groceries', 'Groceries'), ('Furniture & Décor', 'Furniture & Décor'), ('Woman Dress', 'Woman Dress'), ('Kitchen Utensils', 'Kitchen Utensils'), ('Electronics', 'Electronics'), ('Tour', 'Tour')], default='Fashion', max_length=50),
        ),
    ]
